# Generated by Django 4.0.6 on 2022-07-15 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lector', '0001_initial'),
        ('libro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamos',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libro.libro'),
        ),
    ]
